version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" # UI mgmt
    environment:
      RABBITMQ_DEFAULT_USER: youapp
      RABBITMQ_DEFAULT_PASS: youapp
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    volumes:
      # ⬇️ mount folder uploads di host -> /app/uploads di container
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:3001/api"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

volumes:
  mongo_data:
